// Agragegar array de productos

const products = [
    {
        id: 1,
        titulo: 'Buenos Aires',
        precio: 1600,
        descripcion: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',
        img: '',
        category: 'destilados',
    },
    {
        id: 2,
        titulo: 'Retinga',
        precio: 1450,
        descripcion: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',
        img: '',
        category: 'destilados',
    },
    {
        id: 3,
        titulo: 'SUR',
        precio: 1300,
        descripcion: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',
        img: '',
        category: 'destilados',
    },
    {
        id: 4,
        titulo: 'El Alquimista',
        precio: 1400,
        descripcion: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',
        img: '',
        category: 'destilados',
    },
    {
        id: 5,
        titulo: 'HILBING',
        precio: 1000,
        descripcion: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',
        img: '',
        category: 'destilados',
    },
    {
        id: 6,
        titulo: 'Apostoles 950',
        precio: 1600,
        descripcion: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',
        img: '',
        category: 'destilados',
    },
    {
        id: 7,
        titulo: 'Heraclito & Macedonio',
        precio: 1200,
        descripcion: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',
        img: '',
        category: 'destilados',
    },
    {
        id: 8,
        titulo: 'COMUNAL',
        precio: 1400,
        descripcion: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',
        img: '',
        category: 'destilados',
    },
    {
        id: 9,
        titulo: 'ENEBRO',
        precio: 140,
        descripcion: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',
        img: '',
        category: 'botanicos',
    },
    {
        id: 10,
        titulo: 'CARDAMOMO',
        precio: 140,
        descripcion: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',
        img: '',
        category: 'botanicos',
    },
    {
        id: 11,
        titulo: 'CORIANDRO',
        precio: 140,
        descripcion: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',
        img: '',
        category: 'botanicos',
    },
    {
        id: 12,
        titulo: 'RAIZ DE ANGELICA',
        precio: 140,
        descripcion: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',
        img: '',
        category: 'botanicos',
    },
    {
        id: 13,
        titulo: 'CANELA',
        precio: 140,
        descripcion: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',
        img: '',
        category: 'botanicos',
    },
    {
        id: 14,
        titulo: 'PIMIENTA DE JAMAICA',
        precio: 140,
        descripcion: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',
        img: '',
        category: 'botanicos',
    },
    {
        id: 15,
        titulo: 'KIT DE MIXOLOGIA',
        precio: 140,
        descripcion: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',
        img: '',
        category: 'insumos',
    },
    {
        id: 16,
        titulo: 'COPAS',
        precio: 140,
        descripcion: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',
        img: '',
        category: 'insumos',
    },
    {
        id: 17,
        titulo: 'PORTA VASOS',
        precio: 140,
        descripcion: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',
        img: '',
        category: 'insumos',
    },
    {
        id: 18,
        titulo: 'ESTERILLA',
        precio: 140,
        descripcion: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',
        img: '',
        category: 'insumos',
    },
    {
        id: 19,
        titulo: 'PASO DE LOS TOROS',
        precio: 140,
        descripcion: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',
        img: '',
        category: 'tonicas',
    },
    {
        id: 20,
        titulo: 'SCHWEPPES',
        precio: 140,
        descripcion: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',
        img: '',
        category: 'tonicas',
    },
    {
        id: 21,
        titulo: 'FEVER TREE',
        precio: 140,
        descripcion: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',
        img: '',
        category: 'tonicas',
    },
    {
        id: 21,
        titulo: 'TONIC',
        precio: 140,
        descripcion: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',
        img: '',
        category: 'tonicas',
    },
    {
        id: 22,
        titulo: 'PINZAS',
        precio: 140,
        descripcion: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',
        img: '',
        category: 'cocteleria',
    },
    {
        id: 23,
        titulo: 'SPLICE',
        precio: 140,
        descripcion: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',
        img: '',
        category: 'cocteleria',
    },
    {
        id: 24,
        titulo: 'JIGGER',
        precio: 140,
        descripcion: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',
        img: '',
        category: 'cocteleria',
    },
    {
        id: 25,
        titulo: 'JCOCTELERA',
        precio: 140,
        descripcion: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',
        img: '',
        category: 'cocteleria',
    },
]